pub_hdrs = {hxx ixx txx}{** -version} hxx{version}

./: $pub_hdrs

hxx{version}: in{version} $src_root/manifest

# Install into the libhello/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libhello/
  install.subdirs = true
}
